name: async_std_rustls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test async_rustls
      run: cargo test --features "use_async_h1,rustls,proxies" --verbose
